version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: healthcareDb
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data